//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartPromotionEngine.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineItem
    {
        public int OrderLineItem_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public string SKU_Id { get; set; }
        public string Product_Id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
